import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let imageUrl = "/default-background.jpg"; // Fallback background

  try {
    const apiUrl = process.env.API_URL || "http://localhost:3000";
    const res = await fetch(`${apiUrl}/api/get-latest-image`, {
      method: "GET",
    });

    if (!res.ok) {
      throw new Error(`Failed to fetch latest image: ${res.statusText}`);
    }

    const data = await res.json();
    if (data.success) {
      imageUrl = data.imageUrl;
    } else {
      throw new Error(data.error || "No image URL available.");
    }
  } catch (error) {
    console.error("Error fetching image:", error);
  }

  return (
    <html lang="en">
      <body
        className="antialiased"
        style={{
          backgroundImage: `url(${imageUrl})`,
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        {children}
      </body>
    </html>
  );
}
